version: "3.9"
services:
  db:
    image: postgres
    container_name: db
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  api:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    container_name: api
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
  frontend:
    image: nginx:alpine
    container_name: frontend
    ports:
      - 4000:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend:/app
