TypeTransaction.find_or_create_by(type_code: 1, description: 'Débito', label: 'Entrada', value: true)
TypeTransaction.find_or_create_by(type_code: 2, description: 'Boleto', label: 'Saída', value: false)
TypeTransaction.find_or_create_by(type_code: 3, description: 'Financiamento', label: 'Saída', value: false)
TypeTransaction.find_or_create_by(type_code: 4, description: 'Crédito', label: 'Entrada', value: true)
TypeTransaction.find_or_create_by(type_code: 5, description: 'Recebimento Empréstimo', label: 'Entrada', value: true)
TypeTransaction.find_or_create_by(type_code: 6, description: 'Vendas', label: 'Entrada', value: true)
TypeTransaction.find_or_create_by(type_code: 7, description: 'Recebimento TED', label: 'Entrada', value: true)
TypeTransaction.find_or_create_by(type_code: 8, description: 'Recebimento DOC', label: 'Entrada', value: true)
TypeTransaction.find_or_create_by(type_code: 9, description: 'Aluguel', label: 'Saída', value: false)
